export const TEST_SUBCOMMAND_PROTOCOLS = Object.freeze({
  soumettre_atk: "SCALING_ATK",
  soumettre_def: "SCALING_DEF",
  soumettre_crit_rate: "CRIT_RATE_REAL",
  soumettre_crit_dmg: "CRIT_DMG_REAL",
  soumettre_buff: "BUFF_STACKING",
  soumettre_status: "STATUS_PROC_RATE",
  soumettre_multihit: "MULTI_HIT_SNAPSHOT",
  soumettre_cooldown: "COOLDOWN_REAL",
  soumettre_uptime: "BUFF_UPTIME",
  soumettre_interaction: "INTERACTION_AB",
  soumettre_arme_skill: "WEAPON_SKILL_DELTA",
  soumettre_ordre: "ORDER_OF_USE",
  soumettre_fenetre: "DAMAGE_WINDOW",
  soumettre_tag_swap: "TAG_SWAP_IMPACT",
  "systeme:tag_to_burst": "TAG_TO_BURST_CHAIN",
  "systeme:tag_window": "TAG_WINDOW_GAIN",
  "systeme:costume": "COSTUME_IMPACT",
  "systeme:potentiel": "POTENTIAL_IMPACT",
  "systeme:uptime_buff": "BUFF_REAL_UPTIME",
  "systeme:uptime_debuff": "DEBUFF_REAL_UPTIME",
  "systeme:stat_priority": "STAT_PRIORITY_DELTA",
  "systeme:boss_pressure": "BOSS_PRESSURE_DELTA",
  "systeme:burst_state": "BURST_STATE_DELTA",
  "systeme:element_matchup": "ELEMENT_MATCHUP_DELTA",
  "systeme:res_shred": "RES_SHRED_DELTA",
  "systeme:phase_window": "PHASE_SPECIFIC_WINDOW_DELTA",
  "systeme:boss_interrupt": "BOSS_INTERRUPT_PENALTY",
  "systeme:burst_trigger_weapon": "BURST_TRIGGER_WEAPON_DELTA",
  "systeme:burst_hold": "BURST_WINDOW_HOLD_VALUE",
  "systeme:combined_skill": "COMBINED_SKILL_DELTA",
  "systeme:evade_bonus": "SUCCESSFUL_EVADE_BONUS_DELTA",
  "systeme:elemental_status": "ELEMENTAL_STATUS_UPTIME",
  "systeme:boss_recovery": "BOSS_PATTERN_RECOVERY_DELTA",
});

export function protocolForTestSubcommand(sub) {
  return TEST_SUBCOMMAND_PROTOCOLS[String(sub || "")] || null;
}
