export const ROUTES = { INTERACTIONS: "/interactions" };
export const KV_KEYS = {
  CHAR_INDEX: "index:characters",
  BOSS_INDEX: "index:bosses",
  CHAR_PREFIX: "char:",
  BOSS_PREFIX: "boss:",
  BASE_META: "meta:base",
  TIERLIST: "meta:tierlist",
  TIERLIST_LIVE: "meta:tierlist:live",
  NOUVEAUTES: "meta:nouveautes",
  SOURCE_REPORT: "meta:source-report",
  MEDIA_REPORT: "meta:media-report",
  SYNC_REPORT: "meta:sync-report",
  BOT_STATS: "meta:stats-bot:live",
  TEST_DISABLED: "meta:test:disabled",
  TEST_LOCKED: "meta:test:locked",
  TEST_PUBLISHED_INDEX: "meta:test:published:index",
  SCI_CHAR_INDEX: "science:index:characters",
  SCI_CHAR_PREFIX: "science:char:",
  SCI_KIT_INDEX: "science:index:weapon-kits",
  SCI_KIT_PREFIX: "science:kit:",
  SCI_SKILL_INDEX: "science:index:skills",
  SCI_SKILL_PREFIX: "science:skill:",
  SCI_BURST_EFFECTS: "science:meta:burst-effects",
  SCI_COMBINED_ATTACKS: "science:meta:combined-attacks",
  SCI_EVADE_RULES: "science:meta:evade-rules",
  SCI_BOSS_INDEX: "science:index:bosses",
  SCI_BOSS_PREFIX: "science:boss:",
  SCI_BOSS_PHASE_INDEX: "science:index:boss-phases",
  SCI_BOSS_PHASE_PREFIX: "science:boss-phase:",
  SCI_WEAPON_INDEX: "science:index:equippable-weapons",
  SCI_WEAPON_PREFIX: "science:weapon:",
  SCI_ELEMENTS: "science:meta:elements",
  SCI_STATUSES: "science:meta:statuses",
  SCI_SCENARIOS: "science:meta:scenarios",
};
export const ADMIN_ROLE_ID = "1473653456446291998";
export const COMPONENT_IDS = {
  PERSO_TAB: "perso:tab",
  PERSO_SELECT: "perso:select",
  PERSO_SKILL_WEAPON: "perso:skill_weapon",
  PERSO_POT_WEAPON: "perso:pot_weapon",
  PERSO_COSTUME_SELECT: "perso:costume_select",
  PERSO_SKILL_PAGE: "perso:skill_page",
  PERSO_POT_PAGE: "perso:pot_page",
  BOSS_SELECT: "boss:select",
  RAID_TYPE: "raid:type",
  RAID_BOSS_PICK: "raid:boss_pick",
  RAID_BACK: "raid:back",
  RAID_CREATE: "raid:create",
  RAID_JOIN: "raid:join",
  RAID_ROLE: "raid:role",
  RAID_LEAVE: "raid:leave",
  RAID_TOGGLE: "raid:toggle",
  RAID_DELETE: "raid:delete",
  RAID_EDIT: "raid:edit",
};
export const TABS = ["overview","gameplay","progression","stats","skills","potentiels","costumes"];
